#!/usr/bin/env python3
"""Gera as tabelas detalhadas (Markdown, PT e EN) a partir de data/processed/*.json|csv.

Saída: docs/tabelas.pt.md e docs/tables.en.md  (arquivos gerados — não editar à mão)
Uso: python -m eleicao2026.report
"""
import csv
import json

from eleicao2026 import config as C
from eleicao2026.config import UFN

CAND = {"FLAVIO BOLSONARO": "Flávio Bolsonaro", "LULA": "Lula", "RONALDO CAIADO": "Ronaldo Caiado",
        "ESCRITOR AUGUSTO CURY": "Augusto Cury", "RENAN SANTOS": "Renan Santos", "ZEMA": "Romeu Zema",
        "SAMARA": "Samara", "CLARIANA BARAO": "Clariana Barão", "HERTZ DIAS": "Hertz Dias",
        "EDMILSON COSTA": "Edmilson Costa", "VETERINÁRIO WILSON GRASSI": "Wilson Grassi",
        "RUI COSTA PIMENTA": "Rui Costa Pimenta"}

L = {
    "pt": dict(
        title="Tabelas detalhadas (geradas automaticamente)",
        intro="Arquivo gerado por `python -m eleicao2026.report`. Dados: `data/processed/`. Não editar à mão.",
        s1="1. Resultado do 1º turno (apuração atual)", s2="2. Backtest: projeção com 85% apurado × resultado final",
        s3="3. Pesquisas de 2º turno e erro das pesquisas de 1º turno", s4="4. Para onde vão os eleitores dos eliminados",
        s5="5. Modelo histórico (M3)", s6="6. Previsão por UF", s7="7. Distribuição das simulações",
        s8="8. Sensibilidade", cand="Candidato", votes="Votos", pct="% válidos", par="Parcial (85%)", proj="Projeção",
        fin="Final", err="Erro (pp)", uf="UF", inst="Instituto", date="Data (fim)", valid="% de Lula nos válidos (2 cand.)",
        e1t="Erro do 1º turno (margem, pp)", comp="Componente", weight="Peso", mean="Lula % (média)",
        ci90="IC 90% de Lula", pwin="P(Lula vence)", med="Margem mediana (votos)", q="Quantil", ens="Ensemble",
        year="Ano", leader="Líder 1º turno", l1t="% líder 1T", s1t="% 2º colocado 1T", lead2="Líder entre os 2 (1T)",
        l2t="% líder 2T", name="Estado", reg="Região", v1t="Válidos 1T (proj.)", l1="Lula 1T", f1="Flávio 1T",
        l2="Lula 2T (mediana)", pwinuf="P(Lula vence na UF)", bin="Faixa de Lula", thr="Lula acima de",
        marg="Margem de Flávio maior que", weights="Pesos", scen="Cenário", lpct="Lula %", margin="Margem Lula − Flávio (votos)",
        src="Fonte(s)", toflav="→ Flávio (% dos válidos)", decl="Declara voto", national="Nacional",
        w_alvo="Votos válidos 1T (proj.)", w_win="Lula vence",
    ),
    "en": dict(
        title="Detailed tables (auto-generated)",
        intro="File generated by `python -m eleicao2026.report`. Data: `data/processed/`. Do not edit by hand.",
        s1="1. First-round result (current count)", s2="2. Backtest: projection at 85% counted vs. final result",
        s3="3. Runoff polls and first-round poll error", s4="4. Where the eliminated candidates' voters go",
        s5="5. Historical model (M3)", s6="6. Forecast by state", s7="7. Distribution of simulations",
        s8="8. Sensitivity", cand="Candidate", votes="Votes", pct="% valid", par="Partial (85%)", proj="Projection",
        fin="Final", err="Error (pp)", uf="State", inst="Pollster", date="Date (end)", valid="Lula % of valid (2 cand.)",
        e1t="First-round error (margin, pp)", comp="Component", weight="Weight", mean="Lula % (mean)",
        ci90="Lula 90% CI", pwin="P(Lula wins)", med="Median margin (votes)", q="Quantile", ens="Ensemble",
        year="Year", leader="Round-1 leader", l1t="Leader % R1", s1t="Runner-up % R1", lead2="Leader among two (R1)",
        l2t="Leader % R2", name="State name", reg="Region", v1t="Valid R1 (proj.)", l1="Lula R1", f1="Flávio R1",
        l2="Lula R2 (median)", pwinuf="P(Lula wins state)", bin="Lula range", thr="Lula above",
        marg="Flávio margin greater than", weights="Weights", scen="Scenario", lpct="Lula %", margin="Lula − Flávio margin (votes)",
        src="Source(s)", toflav="→ Flávio (% of valid)", decl="Declares a vote", national="National",
        w_alvo="Valid R1 (proj.)", w_win="Lula wins",
    ),
}
SENS_EN = {"Ensemble (base)": "Ensemble (base)", "Só M1 (estrutural)": "M1 only (structural)",
           "Só M2 (pesquisas corrigidas)": "M2 only (adjusted polls)", "Só M3 (histórico)": "M3 only (historical)",
           "Pesos iguais": "Equal weights", "Mais peso nas pesquisas (M2 60%)": "More weight on polls (M2 60%)",
           "Mais peso no estrutural (M1 70%)": "More weight on structural (M1 70%)"}
SCEN_EN = {
    "M1 base (assimetria 0,5; comparecimento 2022)": "M1 base (asymmetry 0.5; 2022 turnout)",
    "M1: comparecimento dos eliminados = pesquisa literal": "M1: eliminated voters' turnout = poll as stated",
    "M1: bases mantêm 100% (sem mobilização pró-Bolsonaro de 2022)": "M1: bases keep 100% (no 2022 pro-Bolsonaro mobilization)",
    "M1: mobilização de 2022 se repete por inteiro": "M1: 2022 mobilization repeats in full",
    "M1: eliminados 50/50": "M1: eliminated split 50/50",
    "M1: eliminados como em 2022 (48% Bolsonaro)": "M1: eliminated split as in 2022 (48% Bolsonaro)",
    "M1: eliminados 10 pp mais pró-Flávio": "M1: eliminated 10 pp more pro-Flávio",
    "M1: eliminados 10 pp mais pró-Lula": "M1: eliminated 10 pp more pro-Lula",
    "M1: sem inclinação regional": "M1: no regional tilt",
    "M1: todos os eliminados votam em Lula (limite)": "M1: all eliminated vote for Lula (bound)"}


def fmt(n, lang):
    s = f"{n:,.0f}"
    return s.replace(",", ".") if lang == "pt" else s


def pct(x, d=2, lang="pt"):
    s = f"{100*x:.{d}f}%"
    return s.replace(".", ",") if lang == "pt" else s


def tbl(head, rows, align=None):
    align = align or ["l"] + ["r"] * (len(head) - 1)
    sep = {"l": "---", "r": "---:"}
    out = ["| " + " | ".join(head) + " |", "|" + "|".join(sep[a] for a in align) + "|"]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return "\n".join(out) + "\n"


def build(lang):
    t = L[lang]
    res = json.loads((C.PROCESSED / "resumo_2turno.json").read_text())
    bt = json.loads((C.PROCESSED / "backtest_1turno.json").read_text())
    meta = json.loads((C.PROCESSED / "apuracao_meta.json").read_text())
    bt_uf = list(csv.DictReader(open(C.PROCESSED / "backtest_1turno_uf.csv")))
    P = lambda x, d=2: pct(x, d, lang)  # noqa: E731
    F = lambda n: fmt(n, lang)  # noqa: E731
    X = lambda v, spec: (format(v, spec).replace('.', ',') if lang == 'pt' else format(v, spec))  # noqa: E731
    o = [f"# {t['title']}\n", t["intro"] + "\n"]

    o.append(f"## {t['s1']}\n")
    o.append(f"TSE {meta['tse_dg'] if 'tse_dg' in meta else ''} {meta['tse_hg']} — "
             f"{meta['pct_secoes_apuradas']}% seções; {F(meta['votos_validos'])} válidos.\n" if lang == "pt" else
             f"TSE {meta['tse_hg']} — {meta['pct_secoes_apuradas']}% of polling stations; "
             f"{F(meta['votos_validos'])} valid votes.\n")
    vv = meta["votos_validos"]
    o.append(tbl([t["cand"], t["votes"], t["pct"]],
                 [[CAND.get(k, k.title()), F(v), P(v / vv)] for k, v in
                  sorted(meta["votos_candidatos"].items(), key=lambda x: -x[1])]))

    o.append(f"## {t['s2']}\n")
    nat = [[t["national"] + " — Lula", P(bt["parcial"]["lula"]), P(bt["projetado"]["lula"]), P(bt["final"]["lula"]),
            f"{X(bt['erro_projecao_pp']['lula'], '+.2f')}"],
           [t["national"] + " — Flávio", P(bt["parcial"]["flavio"]), P(bt["projetado"]["flavio"]),
            P(bt["final"]["flavio"]), f"{X(bt['erro_projecao_pp']['flavio'], '+.2f')}"]]
    o.append(tbl(["", t["par"], t["proj"], t["fin"], t["err"]], nat))
    o.append(tbl([t["uf"], t["par"] + " L−F (pp)", t["proj"] + " L−F (pp)", t["fin"] + " L−F (pp)", t["err"] + " [proj]"],
                 [[r["uf"].upper(), f"{X(100*(float(r['lula_parcial'])-float(r['flavio_parcial'])), '+.1f')}",
                   f"{X(100*(float(r['lula_proj'])-float(r['flavio_proj'])), '+.1f')}",
                   f"{X(100*(float(r['lula_final'])-float(r['flavio_final'])), '+.1f')}",
                   f"{X(float(r['erro_margem_proj_pp']), '+.2f')}"] for r in
                  sorted(bt_uf, key=lambda r: -float(r["validos_final"]))]))

    o.append(f"## {t['s3']}\n")
    o.append(tbl([t["inst"], t["date"], "Lula", "Flávio", t["valid"], t["e1t"]],
                 [[r["pollster"], r["data"], f"{X(r['l'], '.1f')}", f"{X(r['f'], '.1f')}", P(r["lula_valido"], 1),
                   (f"{X(100*res['erro_pesquisas_1t'][r['pollster']]['err_margem'], '+.1f')}"
                    if r["pollster"] in res["erro_pesquisas_1t"] else "")] for r in res["pesquisas_2t"]]))

    o.append(f"## {t['s4']}\n")
    o.append(tbl([t["cand"], t["w_alvo"], t["src"], t["toflav"], t["decl"]],
                 [[CAND.get(r["candidato"], r["candidato"].title()), F(r["votos_validos_1t"]), r["fonte"],
                   P(r["para_flavio"], 1), P(r["declara_voto"], 0)] for r in res["transferencia"]],
                 ["l", "r", "l", "r", "r"]))

    o.append(f"## {t['s5']}\n")
    o.append(tbl([t["year"], t["leader"], t["l1t"], t["s1t"], t["lead2"], t["l2t"]],
                 [[h["ano"], h["lider"], f"{X(h['pct_lider_1t'], '.2f')}", f"{X(h['pct_segundo_1t'], '.2f')}",
                   f"{X(100*h['pct_lider_1t']/(h['pct_lider_1t']+h['pct_segundo_1t']), '.1f')}", f"{X(h['pct_lider_2t'], '.2f')}"]
                  for h in res["historico"]]))

    o.append(f"## {t['s6']}\n")
    o.append(tbl([t["uf"], t["name"], t["reg"], t["v1t"], t["l1"], t["f1"], t["l2"], t["ci90"], t["pwinuf"]],
                 [[r["uf"].upper(), r["nome"], r["regiao"], F(r["v1"]), P(r["l1"], 1), P(r["f1"], 1), P(r["l2"], 1),
                   f"{P(r['lo'], 1)} – {P(r['hi'], 1)}", P(r["p"], 0)] for r in
                  sorted(res["uf"], key=lambda r: -r["v1"])], ["l", "l", "l", "r", "r", "r", "r", "r", "r"]))

    o.append(f"## {t['s7']}\n")
    Q = ["0.025", "0.05", "0.25", "0.5", "0.75", "0.95", "0.975"]
    o.append(tbl([t["q"], t["ens"], "M1", "M2", "M3"],
                 [[f"{X(float(q)*100, '.1f')}%", P(res["share_lula_quantis"][q])] +
                  [P(res["componentes"][c]["quantis"][q]) for c in ("M1", "M2", "M3")] for q in Q]))
    o.append(tbl([t["comp"], t["weight"], t["mean"], t["ci90"], t["pwin"], t["med"]],
                 [[c, P(res["pesos"][c], 0), P(res["componentes"][c]["media"]),
                   f"{P(res['componentes'][c]['quantis']['0.05'])} – {P(res['componentes'][c]['quantis']['0.95'])}",
                   P(res["componentes"][c]["p_lula"], 1), F(res["componentes"][c]["margem_mediana"])]
                  for c in ("M1", "M2", "M3")]))
    o.append(tbl([t["bin"], t["ens"], "M1", "M2", "M3"],
                 [[f"{X(b['lo']*100, '.0f')}–{X(b['hi']*100, '.0f')}%", P(b["ens"], 1), P(b["M1"], 1), P(b["M2"], 1), P(b["M3"], 1)]
                  for b in res["histograma"]]))
    o.append(tbl([t["thr"], t["ens"], "M1", "M2", "M3"],
                 [[f"{X(b['limiar']*100, '.0f')}%", P(b["ens"], 1), P(b["M1"], 1), P(b["M2"], 1), P(b["M3"], 1)]
                  for b in res["limiares"]]))
    o.append(tbl([t["marg"], t["ens"], "M1", "M2", "M3"],
                 [[F(b["margem"]), P(b["ens"], 1), P(b["M1"], 1), P(b["M2"], 1), P(b["M3"], 1)]
                  for b in res["margens_flavio"]]))

    o.append(f"## {t['s8']}\n")
    o.append(tbl([t["weights"], t["mean"], t["pwin"]],
                 [[(SENS_EN.get(s["rotulo"], s["rotulo"]) if lang == "en" else s["rotulo"]), P(s["lula_media"]),
                   P(s["p_lula"], 1)] for s in res["sensibilidade_pesos"]]))
    o.append(tbl([t["scen"], t["lpct"], t["margin"]],
                 [[(SCEN_EN.get(s["rotulo"], s["rotulo"]) if lang == "en" else s["rotulo"]), P(s["lula_pct"]),
                   F(s["margem"])] for s in res["cenarios_m1"]], ["l", "r", "r"]))
    return "\n".join(o)


def main():
    (C.DOCS / "tabelas.pt.md").write_text(build("pt"))
    (C.DOCS / "tables.en.md").write_text(build("en"))
    print("docs/tabelas.pt.md, docs/tables.en.md")


if __name__ == "__main__":
    main()
